# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mobs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmobs.proto\"o\n\x03Mob\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06health\x18\x02 \x01(\x05\x12\x12\n\nposition_x\x18\x03 \x01(\x05\x12\x12\n\nposition_y\x18\x04 \x01(\x05\x12\x11\n\tin_battle\x18\x05 \x01(\x08\x12\x11\n\tparent_id\x18\x06 \x01(\x05\"\x1d\n\x07MobList\x12\x12\n\x04mobs\x18\x01 \x03(\x0b\x32\x04.Mobb\x06proto3'
)




_MOB = _descriptor.Descriptor(
  name='Mob',
  full_name='Mob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Mob.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='health', full_name='Mob.health', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_x', full_name='Mob.position_x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_y', full_name='Mob.position_y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_battle', full_name='Mob.in_battle', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='Mob.parent_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=125,
)


_MOBLIST = _descriptor.Descriptor(
  name='MobList',
  full_name='MobList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mobs', full_name='MobList.mobs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=156,
)

_MOBLIST.fields_by_name['mobs'].message_type = _MOB
DESCRIPTOR.message_types_by_name['Mob'] = _MOB
DESCRIPTOR.message_types_by_name['MobList'] = _MOBLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mob = _reflection.GeneratedProtocolMessageType('Mob', (_message.Message,), {
  'DESCRIPTOR' : _MOB,
  '__module__' : 'mobs_pb2'
  # @@protoc_insertion_point(class_scope:Mob)
  })
_sym_db.RegisterMessage(Mob)

MobList = _reflection.GeneratedProtocolMessageType('MobList', (_message.Message,), {
  'DESCRIPTOR' : _MOBLIST,
  '__module__' : 'mobs_pb2'
  # @@protoc_insertion_point(class_scope:MobList)
  })
_sym_db.RegisterMessage(MobList)


# @@protoc_insertion_point(module_scope)
