# Generated by Django 4.2.2 on 2023-06-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Name')),
                ('description', models.CharField(default='Common creature', max_length=511, verbose_name='Description')),
                ('health', models.IntegerField(verbose_name='Health')),
                ('attack', models.IntegerField(verbose_name='Attack')),
                ('activity', models.IntegerField(choices=[(0, 'Peaceful'), (1, 'Neutral'), (2, 'Agressive')], default=1, verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Creature',
                'verbose_name_plural': 'Creatures',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=24, unique=True, verbose_name='Username')),
                ('health', models.IntegerField(default=35, verbose_name='Health')),
                ('attack', models.IntegerField(default=5, verbose_name='Attack')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=511, unique=True, verbose_name='Description')),
                ('background', models.FileField(upload_to='./media/', verbose_name='Map Image')),
                ('allowed_creatures', models.ManyToManyField(help_text='Ocurred mobs for this location', related_name='residence', to='network_model.creature')),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
            },
        ),
        migrations.CreateModel(
            name='FightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Ended')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Result')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_on_map', to='network_model.location', verbose_name='Location')),
                ('mobs', models.ManyToManyField(to='network_model.creature', verbose_name='Mobs')),
                ('players', models.ManyToManyField(related_name='fights', to='network_model.user', verbose_name='Players')),
            ],
            options={
                'verbose_name': 'Fight',
                'verbose_name_plural': 'Fights',
            },
        ),
    ]
