# Generated by Django 4.2.2 on 2023-06-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='network_model.location', verbose_name='Current location'),
        ),
        migrations.AlterField(
            model_name='fightlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fights_on_map', to='network_model.location', verbose_name='Location'),
        ),
    ]
