# Generated by Django 4.2.2 on 2023-06-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightlog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_on_map', to='network_model.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='fightlog',
            name='mobs',
            field=models.ManyToManyField(to='network_model.creature', verbose_name='Mobs'),
        ),
        migrations.AlterField(
            model_name='fightlog',
            name='players',
            field=models.ManyToManyField(related_name='fights', to='network_model.user', verbose_name='Players'),
        ),
    ]
