# Generated by Django 4.2.2 on 2023-06-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_model', '0002_user_current_location_alter_fightlog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
